[metadata]
# 元数据
name = aclnn-gen
version = 0.0.6
author = LBenedict
author_email = 804420614@qq.com
description = A tool to automatically generate Ascend CANN (ACLNN) C++ test projects.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://gitee.com/lbenedict/aclnn-gen
license = MIT License
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent
    Topic :: Software Development :: Code Generators
    Topic :: Scientific/Engineering :: Artificial Intelligence

[options]
# 项目的包结构和依赖
packages = find:
python_requires = >=3.8

[options.entry_points]
console_scripts =
    aclnngen = aclnn_gen.aclnngen:main