#!/usr/bin/env python3

import argparse
import csv
import sys
from collections import defaultdict


def load_rows(path):
    rows = []
    with open(path, "r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append(row)
    return rows


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", required=True, help="Path to all_prof.csv generated by get_prof.py")
    args = parser.parse_args()

    rows = load_rows(args.csv)
    grouped = defaultdict(dict)
    for row in rows:
        case_name_raw = row["case_name"]
        # strip timestamp suffix if present
        case_name = case_name_raw[:-15] if len(case_name_raw) > 15 else case_name_raw
        target = row["target"]
        grouped[case_name][target] = float(row["time_use"])

    failures = []
    missing = []
    for case_name, payload in sorted(grouped.items()):
        custom = payload.get("custom")
        builtin = payload.get("built-in")
        if custom is None or builtin is None:
            missing.append(case_name)
            continue
        if custom > builtin:
            failures.append((case_name, custom, builtin))

    if missing:
        print("missing performance pairs:")
        for case_name in missing:
            print(case_name)

    if failures:
        print("performance regressions found:")
        for case_name, custom, builtin in failures:
            print(f"{case_name}: custom={custom}us builtin={builtin}us")
        sys.exit(1)

    print("all compared cases passed: custom performance is not lower than builtin")


if __name__ == "__main__":
    main()
