#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
SUITE_DIR=$(cd "${SCRIPT_DIR}/.." && pwd)
ASCENDOPTEST_DIR=$(cd "${SUITE_DIR}/.." && pwd)

if [[ -z "${ASCEND_HOME_PATH:-}" ]]; then
    if [[ -d "/usr/local/Ascend/cann-9.0.0-beta.2" ]]; then
        export ASCEND_HOME_PATH="/usr/local/Ascend/cann-9.0.0-beta.2"
    else
        export ASCEND_HOME_PATH="/usr/local/Ascend/cann"
    fi
fi

if [[ -f "${ASCEND_HOME_PATH}/set_env.sh" ]]; then
    # shellcheck disable=SC1090
    source "${ASCEND_HOME_PATH}/set_env.sh"
fi

if [[ -z "${ASCEND_CUSTOM_OPP_PATH:-}" ]]; then
    for vendor_path in \
        "${ASCEND_HOME_PATH}/opp/vendors/prelu_custom" \
        "/usr/local/Ascend/opp/vendors/prelu_custom" \
        "${ASCEND_HOME_PATH}/opp/vendors/prelu_nn" \
        "/usr/local/Ascend/opp/vendors/prelu_nn"; do
        if [[ -f "${vendor_path}/op_api/include/aclnn_prelu.h" ]]; then
            export ASCEND_CUSTOM_OPP_PATH="${vendor_path}"
            break
        fi
    done
fi

if [[ -n "${ASCEND_CUSTOM_OPP_PATH:-}" && -f "${ASCEND_CUSTOM_OPP_PATH}/include/aclnn_prelu.h" ]]; then
    ASCEND_CUSTOM_OPAPI_PATH="${ASCEND_CUSTOM_OPP_PATH}"
elif [[ -n "${ASCEND_CUSTOM_OPP_PATH:-}" && -f "${ASCEND_CUSTOM_OPP_PATH}/op_api/include/aclnn_prelu.h" ]]; then
    ASCEND_CUSTOM_OPAPI_PATH="${ASCEND_CUSTOM_OPP_PATH}/op_api"
else
    ASCEND_CUSTOM_OPAPI_PATH=""
fi

if [[ -z "${ASCEND_CUSTOM_OPAPI_PATH}" ]]; then
    echo "ERROR: cannot find aclnn_prelu.h under custom OPP package."
    echo "Please install the package generated by code/build.sh first, or set:"
    echo "  export ASCEND_CUSTOM_OPP_PATH=/path/to/opp/vendors/prelu_custom"
    echo "or:"
    echo "  export ASCEND_CUSTOM_OPP_PATH=/path/to/opp/vendors/prelu_custom/op_api"
    exit 1
fi

export LD_LIBRARY_PATH="${ASCEND_CUSTOM_OPAPI_PATH}/lib:${LD_LIBRARY_PATH:-}"

case_args=()
if [[ "${1:-}" == "-n" ]]; then
    case_args=("-n" "${2:?error: -n requires a case name argument}")
fi

python3 "${ASCENDOPTEST_DIR}/run_test.py" \
  -i "${SUITE_DIR}/prototypes/prelu_custom.json" \
  -c "${SUITE_DIR}/cases/prelu_custom_cases.json" \
  -a "${SUITE_DIR}/aclnn_custom_accuracy" \
  --op-path "${ASCEND_CUSTOM_OPAPI_PATH}" \
  --op-type custom \
  --build \
  "${case_args[@]}"
